### ISSUE TITLE
ssh user in await mechanism is harcoded

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#162]
Very nasty harcoded "ubuntu" value

**Comment by 0x2b3bfa0** [comment]
Agreed! If we let users configure the image name, we should also let them configure the user name. Everything would break with other distributions.

Nevertheless, I would prefer to provision a new generic user on boot and hardcode the value instead of letting end users specify their image user name. Ideally, they shouldn't need to care about that.

**Comment by 0x2b3bfa0** [comment]
Only affects the `iterative_machine` and `iteraitve_cml_runner` resources.

This issue made reference to the following values:

https://github.com/iterative/terraform-provider-iterative/blob/66bc9cd08a4ef1b17f068ce7fd296c3065a6c810/iterative/resource_machine.go#L292

https://github.com/iterative/terraform-provider-iterative/blob/e66811de8fce31ebab31e7b35debfefa0bce75c9/iterative/resource_runner.go#L258

Even if those were made configurable, using images based in other distributions still is not a supported use case on those resoures, and there are several other hardcoded `ubuntu` values that predate #70.

https://github.com/iterative/terraform-provider-iterative/blob/e453ea793e854e31d3f4548238ed0b2034d86f6c/iterative/gcp/provider.go#L37

https://github.com/iterative/terraform-provider-iterative/blob/ee030951772005276628c7677cf7f1291585f667/iterative/azure/provider.go#L28

https://cs.github.com/iterative/terraform-provider-iterative/blob/ee030951772005276628c7677cf7f1291585f667/environment/setup.sh#L15-L16
