### ISSUE TITLE
API: wrapper for JS/Python

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#164]
# TPI Rebirth:
Actually we are writing the provider with Golang, what if... we write it in JS?

## How?

We use Cloud vendors SDKs inside TPI but those SDK are actually also available in JS (they are just API calls).
The idea is write the same in JS evaluated by a V8 engine that outputs using the current terraform skeleton.

### before
![image](https://user-images.githubusercontent.com/414967/126325998-a4f3d2ce-81a6-45cc-b740-9b207d3161f0.png)

### After
![image](https://user-images.githubusercontent.com/414967/126326452-746cc7f5-37e9-4195-af26-08871b963115.png)

 ## Benefits:
  - Unified code base
  - JS expertise in the team
  - JS is easier to be found than GO
  - Does not even need terraform if we wish
  - Can be used in the browser (perfect for VScode extension)

**Comment by casperdcl** [comment]
## Cons:

- JS harder to distribute precompiled binaries for than Go

Can we use Python instead?

**Comment by DavidGOrtega** [comment]
> JS harder to distribute precompiled binaries for than Go

I do not think so.

> Can we use Python instead?

Despite that DVC is python our source base is majority JS, said that if we still wanted to use Python I would say that we cant, unless we build a static or dynamic lib to be used by GO

**Comment by 0x2b3bfa0** [comment]
> _Unified code base_

Do we really want to unify [iterative/cml](https://github.com/iterative/cml) with [iterative/terraform-provider-iterative](https://github.com/iterative/terraform-provider-iterative)? I think that both projects are by far more valuable as separate components than when merged together.

- CML is all about interfacing with (SCM) platforms like GitHub, GitLab or Bitbucket.
- This provider is all about interfacing with infrastructure providers, like AWS, Azure or GCP.

Both projects offer a common abstraction over different implementations of the same concepts, but they're mostly self-contained except for [this](https://github.com/iterative/cml/issues/663) and some funny design choices. If we disentangle them so they can work both ensemble and as separate standalone tools, they'll become much more useful.

> _JS expertise in the team_

Well, I don't mind using JavaScript instead of Go or any other programming language, but I don't think we're especially biased towards JavaScript as a team. I'd rather code everything in [MIPS](https://en.wikipedia.org/wiki/MIPS_architecture) assembly. 😄 

> _JS is easier to be found than GO_

Go is probably the _de facto_ programming language for infrastructure. I don't think we're going to find more people with JavaScript and Infrastructure skills than with Go and infrastructure skills. For the same reason, public cloud vendor API implementations on languages other than Go might not be as usable as desired.

> _Does not even need terraform if we wish_

Terraform provides us with a sane dose of abstractions that keep us from maintaining a fair amount of custom code replicating the very same functionality.

> _Can be used in the browser (perfect for VScode extension)_

Shipping Go software with Visual Studio Code extensions doesn't seem to be especially difficult. Terraform [provides a language server](https://github.com/hashicorp/terraform-ls) that does exactly that, and it seems to work pretty well. [GopherJS](https://github.com/gopherjs/gopherjs) could be another option, but it has the potential of introducing some unnecessary complications.

**Comment by 0x2b3bfa0** [comment]
> _JS harder to distribute precompiled binaries for than Go_

That affirmation holds true for any interpreted language, be it Python, JavaScript or [Piet](https://en.wikipedia.org/wiki/Esoteric_programming_language#Piet). Go provides bulky, self-contained binaries that remain compatible with almost any system and don't break easily.

If we ever choose JavaScript for this use case, distributing binaries wouldn't make any sense, as the main point for the migration would be compatibility with browser technologies.

**Comment by 0x2b3bfa0** [comment]
unless we build a static or dynamic lib to be used by GO

It's possible to [write Python modules in Go](https://blog.filippo.io/building-python-modules-with-go-1-5/), but doing it the other way around seems like an atypical use case. Why would we need Go at all if we migrated all our code to any other language?

**Comment by 0x2b3bfa0** [comment]
<img src="https://user-images.githubusercontent.com/414967/126326452-746cc7f5-37e9-4195-af26-08871b963115.png">

Does that mean that we would be keeping the Terraform provider as a frontend for a piece of software written in other language? That deviates for all the standard use cases I am aware of, and doesn't look like something that's easy nor pleasurable to maintain.

Writing a custom Terraform provider with hardcoded infrastructure definitions instead of using the official ones is already an exercise of creativity, but adding another language on the top of that can be a bit too much for the functionality enhancements we'd expect from that change. 🙃

**Comment by 0x2b3bfa0** [comment]
![Frontend vs Backend](https://www.codefriends.es/wp-content/uploads/2020/10/front-end-vs-back-end-1.png)

**Comment by pmrowla** [comment]
> Does not even need terraform if we wish

> Can we use Python instead?

If the provider is going to be rewritten, and done so in a way that it directly uses the aws/azure/gcp APIs, it would be beneficial for the DVC core team if it was rewritten in Python (and could be used directly from DVC as a python package).

Basically, right now we are going to have to support having `.dvc/config` sections that look something like
```
['machine "mymachine"`]
    cloud = aws
    region = us-west
    image = iterative-cml
    ... # support all the possible tpi options
```

From here we have to take that config section and put them into a templated `.tf` and run `terraform apply`. It would be nice if we could avoid having the dependency on terraform (and needing to generate the intermediate `.tf` file) and just do something like
```
import tpi

config = get_machine_config("mymachine") # load the named dvc config section into a dict
tpi.apply(**config)
```

As it stands right now, on the DVC side we're going to have to do our own implementation of `tpi.apply(...)`, where the internals for `apply()` are generate the templated `.tf` from a DVC config, and then running CLI terraform w/the intermediate `.tf` file.

Even if this hypothetical rewrite still includes a dependency on terraform, it would still be beneficial for DVC if the abstraction around wrapping the terraform CLI was separate from core DVC itself (as a part of the `tpi` python package)

**Comment by casperdcl** [comment]
I'd say we could release a `tpi` python package which internally (for now) ships with `.tf` templates and uses `terraform apply`.

Basically

- TPI.go -> TPI.py -> DVC.py
- TPI.go -> CML.js
- TPI.go -> (CML.js? ->) Studio.js

**Comment by 0x2b3bfa0** [comment]
It looks like all the projects depending on cloud execution are written on either Python (DVC) or JavaScript (CML, Studio, ...)

In the case of Studio, it doesn't matter that much because we control the deployment and it would be relatively easy to ship an additional component in any language, but the standalone client side tools should ideally rely on their native ecosystems.

We could either (re)write CML in Python and migrate this project to pure Python, or keep the infrastructure provisioning code in Go and then offer [FFI](https://en.wikipedia.org/wiki/Foreign_function_interface) bindings for both Python and JavaScript.

In any of these cases, it would be pretty safe to get rid of Terraform and use [CloudFormation](https://aws.amazon.com/cloudformation), [Deployment Manager](https://cloud.google.com/deployment-manager) and [Resource Manager](https://azure.microsoft.com/en-us/features/resource-manager) to manage the resource lifecycle on the cloud side instead of the client side. 🤷🏼

**Comment by 0x2b3bfa0** [comment]
If we plan to stick with Go, as per https://github.com/iterative/terraform-provider-iterative/issues/164#issuecomment-903144469, we could provide a Python wrapper package including precompiled wheels.

**Comment by shcheklein** [comment]
Small correction Studio is both - TS and Python. Back-end is written in Python. And I think that will be the place where we will be integrating if it comes to that.

**Comment by aguschin** [comment]
By the way, MLEM will have deployment functionality and we have considered adding ability to provision machines before deployment. So though it's far from a final decision, MLEM (being itself written in Python) could use a python TPI package in the future.
