### ISSUE TITLE
Dynamically detect CML AMI availability

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#167]
Coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/868138422177513533)

For some reason that image is not accessing the ```cml-runner``` command.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, sorry, I missed the purpose of this issue. I've taken the liberty of moving it to the provider repository and changing the title to reflect its actual purpose.

**Comment by 0x2b3bfa0** [comment]
The `cml-runner` script has not been (and probably) won't be part of the AMI, as we discussed in Slack, and this issue is about the check we should introduce to fallback dynamically if the `iterative-cml` image is not found.

```python

if not image:
    if iterative image exists:
        image = iterative
    else:
        image = ubuntu
```

https://github.com/iterative/terraform-provider-iterative/blob/aec00d68d84c82d6bcb81e8da6720732b284811e/iterative/aws/provider.go#L42-L90
