### ISSUE TITLE
WARNING: Error loading config file: .dockercfg: $HOME is not defined

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#40]
AWS ami and azure install

Can be reviewed [here](https://github.com/iterative/cml/runs/1702641793?check_suite_focus=true) under check_container job

**Comment by DavidGOrtega** [comment]
```
export HOME=/root
```

**Comment by DavidGOrtega** [comment]
still

**Comment by DavidGOrtega** [comment]
Seems to be a very recent docker issue https://github.com/docker/cli/pull/2934

**Comment by DavidGOrtega** [comment]
It's appearing again

**Comment by 0x2b3bfa0** [comment]
Digest of the [elbow grease](https://en.wikipedia.org/wiki/Elbow_grease) pathway suggested to get familiar with the machine image building process and increase the bus factor:

> - fix it in the CML AWS AMI:
>   - cml/setup.sh ✅ 
>   - run packer to deploy one image ✅ 
>   - clone the image with the script cml/clone-amis.go 🟡 

I haven't done the last step because I didn't want to replicate the image to other zones unnecessarily, but I think that I have understood well enough what it does. Nevertheless, I'll probably revisit that directory in the near future.
