### ISSUE TITLE
Resource Volumes - Shareable and reusable volumes

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#89]
### Provider-side sibling of https://github.com/iterative/cml/issues/561

The ability to:
 - Reuse a volume across runs
 - Share a volume across machines

**Comment by courentin** [comment]
Hello, I am highly interested by this feature!
How do you imagine this feature to be implemented?

I'd love to contribute to this one if I have enough context to do it.

**Comment by DavidGOrtega** [comment]
👋  @courentin We are actually designing this. Ideally it should be an easy way to declare the volumes in the provider and you can add it into the runner or machine. Let me coma back with the specs if you are willing to help.

**Comment by 0x2b3bfa0** [comment]
> - _Share a volume across machines_

As stated in https://github.com/iterative/cml/issues/561#issuecomment-871019350, [block] volumes can't be shared across machines; that's what block-based and file-based storage systems are for. As long as the shared storage has the same lifecycle as the machine, it could be managed from `cml-runner` so they're created and destroyed together.

> - _Reuse a volume across runs_

This would be a valid use case for [block] volumes, but the lifecycle of volumes should be managed in a different way. If they were being destroyed along with machines, it would be impossible to reuse them _across runs_, so users would need and additional, manual tool to create and destroy volumes as part of the projects' infrastructure.

> - _Share a volume across machines_ **[and]**  _reuse [the same] volume across runs_

That's the purpose of https://github.com/iterative/cml/issues/561, and official Terraform providers already support all the listed solutions.

**Comment by mattlbeck** [comment]
Some inspiration from a related tool: [spotty](https://github.com/spotty-cloud/spotty) has some very useful and configurable [EBS Deletion policies](https://spotty.cloud/docs/providers/aws/ebs-volumes-and-deletion-policies.html).

**Comment by 0x2b3bfa0** [comment]
Closed with #237. We don't support shared block storage (it's impossible) nor persistent block storage (it's not portable), but instead we use object storage that's both shared and persistent, at the cost of performance.

**Comment by pmrowla** [comment]
Is there any documentation on how the object storage is set up in `iterative_task`? Can I define my own volumes/mount points/etc and/or write directly to object storage outside of the `iterative_task` directory sync feature?

Also, when we say that the object storage in `iterative_task` is shared, does that mean it is shared within a single instance of `iterative_task`, meaning that subsequent restarted versions of the task due to spot instance behavior share one "object storage" resource?

Or  does that mean that it can be shared across multiple/all instances of `iterative_task`, meaning that if I create two different `main.tf` files and start two task runners in parallel, I could provide some s3 bucket URL and access the same "object storage" from both tasks? (note that I'm not talking about defining two `iterative_task` resources within the same `main.tf` config)
